### ISSUE TITLE
HUMO

### ISSUE THREAD

**Issue by diemax** [alan2h/sigbiblioteca#1]
Que manera de robar che! JAJA :speak_no_evil:

**Comment by alan2h** [comment]
Si supieras que eso va a ser el sistema de la biblioteca del colegio
nacional

**Comment by alan2h** [comment]
Ni te das una idea de cuanto voy a cobrar jaajajjaajaa

**Comment by alan2h** [comment]
Dame tu numero , cambie el mio. abrazo.

**Comment by diemax** [comment]
Ni Jason Bourne cambia tanto de numero como vos XD
Ahi te mando un mail

**Comment by alan2h** [comment]
3781482464 este es el mio

**Comment by diemax** [comment]
De donde mierda es **3781** jajajaj

**Comment by alan2h** [comment]
Ni idea jajajajaj compre el chip por ahi..
